### ISSUE TITLE
 Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by hcongvan** [DoctorMcKay/node-globaloffensive#4]
i have problem with event 'inspectItemInfo'

csgo.on('inspectItemInfo',function(item){
    ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (D:\SteamGuard\Bot\test.js:149:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

**Comment by DoctorMcKay** [comment]
`csgo` is undefined. Define it.

**Comment by hcongvan** [comment]
Thanks you, DoctorMcKay 
i place it wrong position.
