### ISSUE TITLE
loader.js throw err; -> Cannot find module

### ISSUE THREAD

**Issue by Bl4CkGuuN** [DoctorMcKay/node-globaloffensive#64]
I'm running my script now for almost two years.

Today the ranks weren't updating in the database, so I checked why this could be and manually started the script and got this error:
```
root@ubuntu:~/node_modules/csgobot# node standalonenew.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/node_modules/csgobot/standalonenew.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```
I had this issue a few months back, but didn't do something about that. It just magically worked again somehow :D

**Comment by Bl4CkGuuN** [comment]
im fucking dumb, close it :D
